apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - gateway-crds.yaml
  - cert-manager-install.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - infrastructure.yaml
  - apps.yaml
