apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: default
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lissy93/dashy # {"$imagepolicy": "flux-system:dashy:name"}
              tag: latest # {"$imagepolicy": "flux-system:dashy:tag"}
              digest: "sha256:907c84359d481b1d1693dd0fed986aeb10c4cf384219ee1de91568dec00a9abb" # {"$imagepolicy": "flux-system:dashy:digest"}
            env:
              NODE_ENV: development
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 10
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 15
                  periodSeconds: 30
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: ""
            paths:
              - path: /
                pathType: Prefix
          - host: "dashy.trevorpi.lan"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: configMap
        name: dashy-config
        advancedMounts:
          main:
            main:
              - path: /app/user-data/conf.yml
                subPath: conf.yml
