apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-tls
  namespace: default
spec:
  secretName: home-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: home.trevorleibert.com
  dnsNames:
    - home.trevorleibert.com
    - "*.home.trevorleibert.com"
