apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lissy93/dashy # {"$imagepolicy": "flux-system:dashy:name"}
              tag: latest # {"$imagepolicy": "flux-system:dashy:tag"}
              digest: "" # {"$imagepolicy": "flux-system:dashy:digest"}
            env:
              NODE_ENV: development
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: ""
            paths:
              - path: /
                pathType: Prefix
          - host: "dashy.trevorpi.lan"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /root/container-data/dashy
        globalMounts:
          - path: /app/user-data
