apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glances
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: daemonset
        pod:
          hostPID: true
        containers:
          main:
            image:
              repository: nicolargo/glances
              tag: latest # {"$imagepolicy": "flux-system:dashy-policy:digest"}
            env:
              GLANCES_OPT: "-w"
              TZ: "America/Los_Angeles"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 61208

    ingress:
      main:
        enabled: true
        hosts:
          - host: glances.trevorpi.lan
            paths:
              - path: /
                pathType: Prefix
