apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: glances
  namespace: default
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: daemonset
        pod:
          hostPID: true
        containers:
          main:
            image:
              repository: nicolargo/glances # {"$imagepolicy": "flux-system:glances:name"}
              tag: 4.5.0 # {"$imagepolicy": "flux-system:glances:tag"}
            env:
              GLANCES_OPT: "-w"
              TZ: "America/Los_Angeles"
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/4/status
                    port: 61208
                  initialDelaySeconds: 5
                  periodSeconds: 10
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/4/status
                    port: 61208
                  initialDelaySeconds: 15
                  periodSeconds: 30
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 61208
    ingress:
      main:
        enabled: true
        hosts:
          - host: glances.trevorpi.lan
            paths:
              - path: /
                pathType: Prefix
