apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  interval: 1h
  driftCorrection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        pod:
          hostNetwork: true
          nodeSelector:
            zigbee: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant # {"$imagepolicy": "flux-system:homeassistant:name"}
              tag: 2026.2.1 # {"$imagepolicy": "flux-system:homeassistant:tag"}
            securityContext:
              privileged: true
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        hosts:
          - host: home.trevorpi.lan
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /root/container-data/homeassistant
        globalMounts:
          - path: /config
      dbus:
        enabled: true
        type: hostPath
        hostPath: /run/dbus
        globalMounts:
          - path: /run/dbus
            readOnly: true
