apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zwave
  namespace: default
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        pod:
          nodeSelector:
            zwave: "true"
        containers:
          main:
            image:
              repository: zwavejs/zwave-js-ui # {"$imagepolicy": "flux-system:zwave:name"}
              tag: 11.12.0 # {"$imagepolicy": "flux-system:zwave:tag"}
            securityContext:
              privileged: true
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/zwave
                    port: 8091
                    httpHeaders:
                      - name: Accept
                        value: text/plain
                  initialDelaySeconds: 10
                  periodSeconds: 10
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8091
                    httpHeaders:
                      - name: Accept
                        value: text/plain
                  initialDelaySeconds: 15
                  periodSeconds: 20
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8091
          api:
            port: 3000
    ingress:
      main:
        enabled: true
        hosts:
          - host: zwave.trevorpi.lan
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /root/container-data/zwave-ui
        globalMounts:
          - path: /usr/src/app/store
      zwave-device:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E3038596-if00
        globalMounts:
          - path: /dev/zwave
