apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        pod:
          nodeSelector:
            zwave: "true"
        containers:
          main:
            image:
              repository: zwavejs/zwave-js-ui
              tag: latest # {"$imagepolicy": "flux-system:dashy-policy:digest"}
            securityContext:
              privileged: true

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8091
          api:
            port: 3000

    ingress:
      main:
        enabled: true
        hosts:
          - host: zwave.trevorpi.lan
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: http

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /root/container-data/zwave-ui
        globalMounts:
          - path: /usr/src/app/store

      zwave-device:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-1a86_USB_Single_Serial_58E3038596-if00
        globalMounts:
          - path: /dev/zwave
